---
include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - project: 'pujak/infrastructure/gitlab-ci'
    ref: master
    file:
      - 'jobs/build.yml'
      - 'jobs/review.yml'
      - 'jobs/security.yml'
      - 'jobs/env-cleaner.yml'
      - 'jobs/deploy.yml'


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

    - if: $CI_COMMIT_BRANCH == "dev"
      when: always

    - if: $CI_COMMIT_MESSAGE =~ /skip-ci/
      when: never

    - if: $CI_COMMIT_BRANCH =~ /feature/ && $CI_COMMIT_MESSAGE =~ /CI/
      when: always

    - when: never


stages:
  - operation
  - build
  - review
  - test
  - security
  - deploy


build-image:
  variables:
    DOCKERFILE_PATH: .
