---
include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - project: 'pujak/infrastructure/gitlab-ci'
    ref: master
    file:
      - 'jobs/build.yml'
      - 'jobs/review.yml'
      - 'jobs/security.yml'
      - 'jobs/env-cleaner.yml'
      - 'jobs/deploy.yml'


workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always

    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

    - if: $CI_COMMIT_BRANCH == "dev"
      when: always

    - if: $CI_COMMIT_MESSAGE =~ /skip-ci/
      when: never

    - if: $CI_COMMIT_BRANCH =~ /feature/ && $CI_COMMIT_MESSAGE =~ /CI/
      when: always

    - when: never


stages:
  - operation
  - build
  - review
  - test
  - security
  - deploy


.deploy:
  variables:
    HELM_PATH: .helm/Backend


deploy-db:
  stage: deploy
  extends:
    - .deploy

  variables:
    HELM_PATH: .helm/Database
    KUBE_NAMESPACE: $CI_PROJECT_NAME-static-$CI_COMMIT_BRANCH
    HOST: "$CI_COMMIT_BRANCH.$CI_PROJECT_NAME.$KUBE_HOST"

  script:
    - helm upgrade --set image=$IMAGE_NAME,host=$HOST --namespace $KUBE_NAMESPACE $KUBE_NAMESPACE $HELM_PATH --install --create-namespace
    - echo Database is up and available at $HOST

  environment:
    name: $CI_COMMIT_BRANCH-db
    url: $HOST
    action: start

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_COMMIT_BRANCH == "dev"
      when: manual
    - when: never

