---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timej-api
  labels:
    app: timej-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timej-api
  template:
    metadata:
      labels:
        app: timej-api
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: timej-api
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: timej-api-secret
          resources:
            requests:
              memory: "80Mi"
              cpu: "10m"
            limits:
              memory: "150Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
