---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: timej-api-cors
config:
  origins:
    - "*"
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
  exposed_headers:
    - X-Auth-Token
  credentials: true
  max_age: 3600
plugin: cors