---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: timej
  POSTGRES_USER: timej
  POSTGRES_PASSWORD: {{ .Values.db_pass }}